version: '3'
services:
  web:
    build: .
    ports:
      - "4000:3000"
    volumes:
      - ./api:/usr/src/peeper
      - bundle:/usr/local/bundle
    command: ./bin/rails-entrypoint.sh
volumes:
  bundle: